### ISSUE TITLE
Function exits without clean used stack

### ISSUE THREAD

**Issue by hiperiondev** [Ratstail91/Toy#105]
In execFnDecl push scope in stack and, at the end of function, pop this.
But, if an error occurs, it exits the function without returning the stack to its original state.

**Comment by hiperiondev** [comment]
is not the correct interpretation. Sorry

**Comment by Ratstail91** [comment]
Actually, I've done something odd here - I want to fix it later, thanks for pointing it out.

TODO: use copyLiteral
