### ISSUE TITLE
Missing advance after while?

### ISSUE THREAD

**Issue by Aimen-Hammou** [Ratstail91/Toy#2]
Hi, 

I was reading the code and I stumbled across the function makeNumber(...) inside lexer.c
Inside the function, you peek if the current char is a '.' meaning the number you are lexing is a float, but after advancing you run a while loop that does nothing and if tested it would probably run an infinite loop.

the lines of code I'm referring to
`
if (peek(lexer) == '.') {
       advance(lexer);
       while(isDigit(lexer));
}
`

**Comment by Ratstail91** [comment]
https://github.com/Ratstail91/Toy/blob/5ed16b263d3ebeb4dc188847cae06af65e7eb03e/source/lexer.c#L142-L145

This seems to be the lines you're referring to - and you're right. I'm not sure how I didn't catch that, however, I'm starting to scratch out the beginnings of version 0.5.0, so 0.4.0 is officially deprecated.

Thanks for your help @Aimen-Hammou !
