### ISSUE TITLE
There may be integer division issues (currently, the remainder is discarded).

### ISSUE THREAD

**Issue by Ratstail91** [Ratstail91/Toy#5]
Is this the desired behaviour?

**Comment by DMClVG** [comment]
I'm confused as to what you mean

``` c
5 / 2 == 2 // true
```

or no?

**Comment by Ratstail91** [comment]
Yes, that's the current behaviour, but I'm wondering if it's desired or not.

I realized that I could possibly alter this after watching a video about the differences between Python 2 and Python 3, so I jotted this issue down for later reference.

**Comment by DMClVG** [comment]
huh. I never knew python had integer divisions return floats.

Personally, I'm indifferent about it

**Comment by Ratstail91** [comment]
This is fine, I'm closing this.
