### ISSUE TITLE
The language only supports ascii, as far as I can tell.

### ISSUE THREAD

**Issue by Ratstail91** [Ratstail91/Toy#6]
This may need to be worked on at some point in the future, especially if it gains traction - for now, it's fine though.

**Comment by DMClVG** [comment]
It should definitely support UTF-8 at some point. For now the compiler should ideally throw out an error if it encounters an non-ASCII character (we don't want the script to behave in weird ways just cause someone decided to put an emoji in their print statement). Should be fairly trivial by just checking the 8th bit for every character
