### ISSUE TITLE
Calling type() on a const segfaults

### ISSUE THREAD

**Issue by eatcomics** [Ratstail91/Toy#60]
To reproduce:
```
var a: int const = 42;
a.type();
```

Result: Segfault

Expected Result: Not that
![segfault](https://user-images.githubusercontent.com/1631533/217882749-664d5337-8167-43c7-9c84-49c25bc20526.jpg)

**Comment by Ratstail91** [comment]
This was patched earlier today - pull the latest commit and try again. If the problem persists, feel free to re-open this.
