### ISSUE TITLE
Toylang didn't support 64-bit integers... until today.

### ISSUE THREAD

**Issue by pxcla** [Ratstail91/Toy#68]
### The Issue

Toy does not support 64-bit integers, in 2023, when 64-bit consumer processors have been out for almost 2 decades.

### The Solution

Add support for 64-bit integers.

### The Surprise

I have done it myself. Here is a screenshot of my version running alongside the standard version 1.1.1.

![image](https://user-images.githubusercontent.com/125165538/221448752-e248a7e9-7e97-4fda-816a-db22592f57a4.png)

### The Question

Would you be interested in my submitting a PR?

**Comment by AaronGlazer** [comment]
Well done, Patrick. Really good stuff. Props to you for taking time out of your week to contribute to the cause.

**Comment by darcagn** [comment]
Are you sure this is necessary? In general, 64-bit integers are used for tasks that require very large or very precise values, such as cryptographic applications, scientific calculations, or large-scale data processing. For everyday tasks such as storing small integers, calculating basic arithmetic operations, or representing simple data types, smaller integer types are usually sufficient. 64-bit integers are not always necessary for every computing task, and their inclusion just increases the cognitive overhead of writing in Toy. As most computing tasks can be accomplished using smaller integer types, such as 8-bit or 16-bit integers, I personally vote for a veto of this feature and to continue with the overall vision of Toy as it is currently implemented.

**Comment by pxcla** [comment]
In order to prevent any possible naysayers from questioning my feat, I would like to show video proof of me building and running Toy64.


https://user-images.githubusercontent.com/125165538/221450935-0e5fa298-8ad1-414a-82c4-8c1f7601ea05.mp4

**Comment by andrewapperley** [comment]
This PR is almost as hot as the Australian summer. Good job Patrick.

**Comment by Bruceleeto** [comment]
I think this is amazing. I always found this limitation of Toy very frustrating being limited to 32-bit. Thank you for making Toy a little bit more better!

**Comment by darcagn** [comment]
> I think this is amazing. I always found this limitation of Toy very frustrating being limited to 32-bit. Thank you for making Toy a little bit more better!

You may downvote my opinion all you want but it is the truth. It's always important to weigh the pros and cons and make an informed decision based on the specific requirements of each project. Wouldn't using 64-bit integers also increase the memory usage of our programs, potentially slowing them down? I think it's important to consider the specific needs of our project and choose the appropriate data types accordingly. While 64-bit integers can be useful in certain situations, we don't want to overcomplicate our code if it's not necessary.

**Comment by andrewapperley** [comment]
Thanks for weighing in @darcagn.

However, this is great news! Toy now has the ability to process 64-bit numbers, meaning that all applications and calculations can benefit from increased accuracy and power. From simple calculations to more advanced operations, Toy is now even more capable than before. This upgrade will be warmly welcomed by anyone who relies on the Toy language, and is a welcome step forward!
Please don’t take away from this triumphant moment we are witnessing.

**Comment by pxcla** [comment]
Thank you, @andrewapperley 

Gentlemen, no arguing or debating, please.
Let's just appreciate that new era, an era of 64-bit computing has been ushered in for Toy, as well as all the possibilities it entails.

![image](https://user-images.githubusercontent.com/125165538/221460141-2b8a43d3-70e2-4bd8-a79f-46d57c652aec.png)

**Comment by darcagn** [comment]
> Thanks for weighing in @darcagn.
> 
> However, this is great news! Toy now has the ability to process 64-bit numbers, meaning that all applications and calculations can benefit from increased accuracy and power. From simple calculations to more advanced operations, Toy is now even more capable than before. This upgrade will be warmly welcomed by anyone who relies on the Toy language, and is a welcome step forward! Please don’t take away from this triumphant moment we are witnessing.

It is not my intention to take away anything from anyone. It is clear by the speed in which this feature was implemented that this project is moving much too fast for those relying on the Toy language. If this PR were accepted I would have no choice but to create a fork without the changes, but continuing with bug fixes. My project requires stability, not a torrent of bleeding edge features. Stable versions are preferred for production environments or critical systems where any downtime or errors could have significant consequences. Using a stable version that has been tested and proven to be stable can help ensure the system remains reliable and functional. The current version of Toy has gone through a rigorous testing process with my project and has been deemed suitable for general use, while this new version is still in a potentially questionable state. 

Is @Ratstail91 willing to maintain both stable and bleeding edge branches of Toy? If not, since Toy has reached a stable 1.0 release, we should deeply reconsider this feature creep.

**Comment by pxcla** [comment]
@darcagn 

I am sorry, but you don't quite understand.

Users relying on the previous 32-bit only behavior can simply stick to the current release version, 1.1.1.

I propose my 64-bit support to be added for version 1.2.0, (as can be seen in the REPL video above).
This is a minor version bump, since it possibly introduces breaking changes to previous projects. However, users should know that there are significant differences between version 1.1.x and 1.2.x. 

Those relying on old behavior can simply use the old version.

Once again, my 64-bit support would be merged for a 1.2.0.

**Comment by andrewapperley** [comment]
The feature is too large for a minor version bump. This would call for a 2.0.0 launch. Is the toy lang community ready for such a divergent from what they are used to?

**Comment by pxcla** [comment]
The final decision for the version number would be up to @Ratstail91.

If it warrants a 2.0.0 launch, so be it.

If it can simply be a 1.2.0, that's fine as well.

This debate over the version number shouldn't get in the way of recognizing the gravity of the new 64-bit support.

**Comment by darcagn** [comment]
> Users relying on the previous 32-bit only behavior can simply stick to the current release version, 1.1.1.
> 
> I propose my 64-bit support to be added for version 1.2.0, (as can be seen in the REPL video above). This is a minor version bump, since it possibly introduces breaking changes to previous projects. However, users should know that there are significant differences between version 1.1.x and 1.2.x.
> 
> Those relying on old behavior can simply use the old version.

I understand perfectly well that 1.1.1 can continue to be used. However, will bug fixes and support patches continue to be provided for a 1.1.x branch? At this time, that answer would be no. If you want this completely unnecessary feature, I think you should just create your own fork of Toy so as to not burden other users relying on Toy's current stability. 64-bit is just completely unnecessary and more often than not, such support creates a crutch for inexperienced programmers as they just grab the biggest tool they can by default and end up creating slow, bloated programs with excessive memory requirements.

**Comment by andrewapperley** [comment]
Have we even considered the ramifications of this change? Yes, it will double the speed of program execution (apple claimed this so why can’t we?) but will reduce the amount of potential toy users. If we can’t support the Dreamcast and raspberry pi then why are we programmers?

**Comment by pxcla** [comment]
@andrewapperley 

The Dreamcast and Raspberry Pi can absolutely be supported.

My 64-bit support was implementing in 100% standard compliant ISO C.

As you know, the Dreamcast SH4 and even the original ARM11 CPU in the Raspberry Pi 1 are still currently supporting by the latest release of gcc. This is not an issue. 64-bit integers will work.

**Comment by andrewapperley** [comment]
@pxcla you’re the best, man. Thanks for taking this on. I agree but also scared. This is a big change and don’t want to rush into it

**Comment by darcagn** [comment]
> @pxcla you’re the best, man. Thanks for taking this on. I agree but also scared. This is a big change and don’t want to rush into it

You should be scared. You don't need to be working with some half-baked implementation of Toy with ridiculous features bolted.

**Comment by andrewapperley** [comment]
What if this doesn’t go the way you planned? What if the suggestion is rejected but then implemented anyway, without your contribution status being added to the language? Is that fair? No the sucks dick! You don’t want that. The language doesn’t want that! And the community doesn’t want that!

Go take your great ideas somewhere else.

//wontfix

**Comment by pxcla** [comment]
@darcagn @andrewapperley 

You know what? I really, really, don't appreciate the negative comments on my contributions.
This code is high quality, and it is battle tested.

If you guys care so much about my 64-bit support tainting the "stability" of this project, I'll just fork it and make my own Toy64 series.
But just you wait... i3-gaps was forked from i3, and who is using plain i3 anymore?

**Comment by pxcla** [comment]
I am closing this issue. Don't need to waste my time with further negativity against my 64-bit contribution.

**Comment by Ratstail91** [comment]
Locking thread due to repeated abuse.
