### ISSUE TITLE
Make a main header for the Toy library

### ISSUE THREAD

**Issue by GabrielGavrilov** [Ratstail91/Toy#72]
Currently in order to use Toy, we have to include its libraries separately.
There should be a main "toy.h" header that does that all separately for you. Kind of like how Lua's C API does it.

**Comment by Ratstail91** [comment]
That's a good idea! I think it should include the core components of the lang:

* Lexer
* Parser
* Compiler
* Interpreter
* Literal
* Literal Array
* Literal Dictionary
* Memory
* Ref String (for completeness)
* Scope (for completeness)
* toy_common.h
* toy_console_colors.h

I'm not certain about the console colors utility header, but that might as well be included for completeness. I'm going to go ahead and whip up a basic implementation right now.
