### ISSUE TITLE
Move the repl code from common.c to the actual repl files.

### ISSUE THREAD

**Issue by Ratstail91** [Ratstail91/Toy#80]

**Comment by hiperiondev** [comment]
For my needs I have separated the REPL code in: https://github.com/hiperiondev/uC-TOY

I particularly prefer to use it on a microcontroller linenoise .
You can see a particular use in: https://github.com/hiperiondev/esp32_toy/blob/main/main/main.c

**Comment by Ratstail91** [comment]
I had to look up linenoise - it's where you get a history of what you've written?

I need to eventually move the repl code out of common.c... I just haven't gotten to it yet lol.

**Comment by hiperiondev** [comment]
History is optional. It has an online editor. It is very small and concise, which is why it already comes in the SDKs of many microcontrollers.

**Comment by Ratstail91** [comment]
OK cool.

**Comment by Ratstail91** [comment]
This was the result of messy code.
