### ISSUE TITLE
Rename the about library

### ISSUE THREAD

**Issue by Ratstail91** [Ratstail91/Toy#81]
So it doesn't clash with Box's meta-info library

**Comment by Add00** [comment]
How about naming it the VersionInfo Library? Since it contains information related to the current version of toy?

**Comment by Ratstail91** [comment]
I was considering calling it the "toy" library.

Though "ToyVersionInfo" or "toy_version_info" could work.

**Comment by Ratstail91** [comment]
Oops, typo in the commit message lol.
