### ISSUE TITLE
Misspelled function name?

### ISSUE THREAD

**Issue by hiperiondev** [Ratstail91/Toy#87]
in toy_scope.c:

bool Toy_isDelcaredScopeVariable(Toy_Scope *scope, Toy_Literal key)

should be Toy_isDeclaredScopeVariable ?

**Comment by Ratstail91** [comment]
Ah crap, that's embarassing. OK, I'm doing a CTRL-F now, will bump minor version and push a release.

**Comment by Ratstail91** [comment]
OK, new release, you should just be able to copy-paste the files into the right positions.
