### ISSUE TITLE
Change #pragma once by guard

### ISSUE THREAD

**Issue by hiperiondev** [Ratstail91/Toy#89]
#pragma is not very well supported on some systems and can cause problems (for example the ESP-IDF plugin in Eclipse fails to index files)

**Comment by Ratstail91** [comment]
What specific systems are lacking pragma support? Can you provide a list?

As far as I'm aware, `#pragma once`, specifically, is fairly widely supported even if `#pragma` in general isn't.

**Comment by Ratstail91** [comment]
I'm assuming you've read this thread already - https://github.com/espressif/idf-eclipse-plugin/issues/590

This seems to be related to your issue in particular, and there doesn't seem to be an easy fix coming on their end.

I could write a quick tool to swap guard methods for you - it shouldn't be too hard. Would you like that @hiperiondev? You'd just have to run it before copying the code over.

Ideally I'd like for your forks to be easy to maintain - maybe even just a copy/paste.

**Comment by hiperiondev** [comment]
It is not critical. I changed it by hand in the fork code. But other compilers for microcontrollers may not support it correctly. Guard is simple, standard and works everywhere.

**Comment by Ratstail91** [comment]
Too late - It's already in the tools directory for you - https://github.com/Ratstail91/Toy/blob/main/tools/changing-of-the-guard.cpp

Build it, then run it like this:

```bash
guard includes/*
```

Should just simply work.
