### ISSUE TITLE
Fuctions may to be a macro

### ISSUE THREAD

**Issue by hiperiondev** [Ratstail91/Toy#92]
Functions Toy_setInterpreterPrint, Toy_setInterpreterAssert and Toy_setInterpreterError are not critical functions and very optional. May be a macro for this should be better.

**Comment by Ratstail91** [comment]
It's true that they're pretty small one-liners, but making them a macro is a bit overboard. I'll make them inline functions instead - the resulting machine code will be the same.

**Comment by Ratstail91** [comment]
Ah wait, I take that back - 

```
C code ordinarily should not use inline. 
```

https://www.gnu.org/software/gnulib/manual/html_node/extern-inline.html

Sorry, I'll leave these as is. Best to leave them for the compiler to optimize.
